### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by rishipudipeddi** [kajchang/StudentVue#15]
@kajchang This morning, I was able to call the code and have it work perfectly. But then in the afternoon, not making any changes to the version or code, I started getting this log of errors after attempting to run it. I saw that there was a version update available, so I did that but nothing changed.

Traceback (most recent call last):
  File "\<frozen importlib._bootstrap>\", line 900, in _find_spec
AttributeError: '_SixMetaPathImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "grades.py", line 3, in <module>
    from studentvue import StudentVue
  File "/home/pi/.local/lib/python3.7/site-packages/studentvue/__init__.py", line 1, in <module>
    from .StudentVue import StudentVue
  File "/home/pi/.local/lib/python3.7/site-packages/studentvue/StudentVue.py", line 1, in <module>
    import zeep
  File "/home/pi/.local/lib/python3.7/site-packages/zeep/__init__.py", line 1, in <module>
    from zeep.client import CachingClient, Client  # noqa
  File "/home/pi/.local/lib/python3.7/site-packages/zeep/client.py", line 5, in <module>
    from zeep.transports import Transport
  File "/home/pi/.local/lib/python3.7/site-packages/zeep/transports.py", line 5, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from six.moves.http_client import (
  File "\<frozen importlib._bootstrap>\", line 983, in _find_and_load
  File "\<frozen importlib._bootstrap>\", line 963, in _find_and_load_unlocked
  File "\<frozen importlib._bootstrap>\", line 902, in _find_spec
  File "\<frozen importlib._bootstrap>\", line 879, in _find_spec_legacy
  File "\<frozen importlib._bootstrap>\", line 449, in spec_from_loader
  File "/usr/lib/python3/dist-packages/six.py", line 216, in is_package
    return hasattr(self.__get_module(fullname), "__path__")
  File "/usr/lib/python3/dist-packages/six.py", line 118, in __getattr__
    _module = self._resolve()
  File "/usr/lib/python3/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.7/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.7/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.7/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.7/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/lib/python3.7/email/utils.py", line 33, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python3.7/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/home/pi/calendar.py", line 4, in <module>
    sv = StudentVue('[username]', '[password]', '[domain name')
TypeError: 'module' object is not callable

**Comment by kaijchang** [comment]
That's a weird issue but I don't know if it has anything to do directly with this library. Did you make any changes to python or install anything that could mess with packages before it stopped working? Knowing nothing about your circumstances, I would try uninstalling and reinstalling this package if it seems to be just a problem with working with this package.

**Comment by rishipudipeddi** [comment]
@kajchang I didn't make any changes to python, and I uninstalled and reinstalled this package a few times and it didn't work. I'm just really confused because absolutely nothing that I can tell was changed. I'm looking back and all I can remember doing is creating a new file that utilized get_calendar(). Should I delete that file?

**Comment by rishipudipeddi** [comment]
@kajchang Okay. I just deleted the calendar file and now every other file works again. What do you think is the source of this issue?

**Comment by kaijchang** [comment]
What was the name of the calendar file?

**Comment by thexpiredpear** [comment]
The name was calendar.py
The code was:
#!/usr/bin/env python
from studentvue import StudentVue
sv = StudentVue('s-pudipeddiri', 'Kit!00aAb8337', 'https://wa-bsd405-psv.edupoint.com/')
print(sv.get_calendar())

**Comment by kaijchang** [comment]
deleted that because it had your credentials in it

**Comment by rishipudipeddi** [comment]
oh god, thanks so much
#!/usr/bin/env python
from studentvue import StudentVue
sv = StudentVue('[usr]', '[pass]', '[domain]')

**Comment by kaijchang** [comment]
I'm not a really an expert in python, but it looks like somehow for this section
File "/usr/lib/python3.7/email/_parseaddr.py", line 16, in
import time, calendar
File "/home/pi/calendar.py", line 4, in
sv = StudentVue('[username]', '[password]', '[domain name')
TypeError: 'module' object is not callable

`/usr/lib/python3.7/email/_parseaddr.py` is trying to import `import time, calendar` but instead of importing the [builtin calendar module](https://docs.python.org/3/library/calendar.html), it's importing your `calendar.py` instead unintentionally which is causing some sort of circular dependency mix up.

**Comment by kaijchang** [comment]
This isn't something I've run into, but I think you should just avoid naming files the same thing as builtin modules.

Didn't actually read this but it looks like it could be relevant : [https://stackoverflow.com/questions/6031584/importing-from-builtin-library-when-module-with-same-name-exists](https://stackoverflow.com/questions/6031584/importing-from-builtin-library-when-module-with-same-name-exists)

**Comment by kaijchang** [comment]
Hope this helped. I definitely learned something today!

**Comment by rishipudipeddi** [comment]
Thank you so much. That was the issue!
