### ISSUE TITLE
URL: <school domain>/Service/PXPCommunication.asmx?WSDL not found

### ISSUE THREAD

**Issue by a-github-account** [kajchang/StudentVue#16]
Here's the full trace:
```
Traceback (most recent call last):
  File "E:\Programming stuff\studentvue\main.py", line 3, in <module>
    sv = StudentVue('<username>', '<password>', '<domain>')
  File "C:\Users\milkyway90\AppData\Local\Programs\Python\Python310\lib\site-packages\studentvue\StudentVue.py", line 60, in __init__
    self.client = zeep.Client(
  File "C:\Users\milkyway90\AppData\Local\Programs\Python\Python310\lib\site-packages\zeep\client.py", line 76, in __init__
    self.wsdl = Document(wsdl, self.transport, settings=self.settings)
  File "C:\Users\milkyway90\AppData\Local\Programs\Python\Python310\lib\site-packages\zeep\wsdl\wsdl.py", line 92, in __init__
    self.load(location)
  File "C:\Users\milkyway90\AppData\Local\Programs\Python\Python310\lib\site-packages\zeep\wsdl\wsdl.py", line 95, in load
    document = self._get_xml_document(location)
  File "C:\Users\milkyway90\AppData\Local\Programs\Python\Python310\lib\site-packages\zeep\wsdl\wsdl.py", line 155, in _get_xml_document
    return load_external(
  File "C:\Users\milkyway90\AppData\Local\Programs\Python\Python310\lib\site-packages\zeep\loader.py", line 89, in load_external
    content = transport.load(url)
  File "C:\Users\milkyway90\AppData\Local\Programs\Python\Python310\lib\site-packages\zeep\transports.py", line 123, in load
    content = self._load_remote_data(url)
  File "C:\Users\milkyway90\AppData\Local\Programs\Python\Python310\lib\site-packages\zeep\transports.py", line 136, in _load_remote_data
    response.raise_for_status()
  File "C:\Users\milkyway90\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://<domain>/Service/PXPCommunication.asmx?WSDL
```

Obviously, the \<username>, \<password>, and \<domain> are my actual username, password, and domain. In the interest of privacy, I would not like to leak my real school portal online, but I would be willing to share it with the repository owner.

**Comment by a-github-account** [comment]
Would like to clarify, my StudentVUE portal seems to use ASPX instead of ASMX. I don't know how much of a difference that makes.

**Comment by a-github-account** [comment]
Tried the old, web-based version and there are still many incompatibilities with my StudentVUE: it's like a totally different service.

**Comment by LoganMD** [comment]
This repo is pretty outdated, as most of us have already graduated from the schools that the synergy information service relied on. I'm looking into ways I can try to maintain it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LoganMD** [comment]
note to self figure out how to remove the outlook watermark

**Comment by kaijchang** [comment]
@a-github-account chiming in here, it's likely that your school district is running an outdated version of StudentVue, which is incompatible with this API client. There's not much we can do with this project, your best approach would be attempting to reverse engineer that older version yourself.
